### ISSUE TITLE
Serialization doesn't work for generic Java `object`s

### ISSUE THREAD

**Issue by ehashman** [gfredericks/vcr-clj#13]
I tried attaching `vcr-clj` to `aleph.http/get`. Here's what it wrote (with redactions) in a cassette:

```clojure
{:calls [{:var-name "aleph.http/get", :arg-key ["https://some-url" {:pool #object[io.aleph.dirigiste.Pool 0x10014459 "io.aleph.dirigiste.Pool@10014459"]}], :return << {:request-time 573, :headers {"server" "TwistedWeb/16.6.0", "content-type" "application/json; charset=UTF-8", "content-length" "19972", "date" "Fri, 09 Dec 2016 15:43:22 GMT"}, :status 200, :keep-alive? true, :connection-time 187, :body #object[java.io.ByteArrayInputStream 0x63793f16 "java.io.ByteArrayInputStream@63793f16"]} >> }
```

When I try to play back the cassette, everything blows up:

```
java.lang.RuntimeException: No reader function for tag object
```

Presumably we'd need to add a reader (or add configuration for readers) in `vcr-clj.cassettes.serialization`.

**Comment by gfredericks** [comment]
arbitrary objects can't generally be deserialized (this is a general point, not something about vcr-clj in particular); e.g., in this case it looks like you have something called a `Pool`, which I assume is a connection pool of some sort? Stateful opaque objects like that can't be meaningfully recreated.

I think what this means for vcr-clj is that you'll want to use a custom arg-key function that removes the pool, since the pool object is not helpful for figuring out which recorded call to use.

Let me know if any of this doesn't make sense.

**Comment by ehashman** [comment]
That definitely makes sense. Longer term, I'd like to write some aleph-specific support for this, but that will probably have to wait until the new year.

Thank you for helping to explain `arg-key-fn` to me! I had a feeling that it was what I wanted but wasn't quite sure.

**Comment by ehashman** [comment]
(That does help, but unfortunately only gets me about half the way because I have a bytestream object in my return response. Since I have other stuff to redact from the recordings, I just removed it and that hack's got this working for now.)

**Comment by gfredericks** [comment]
removing the bytestream from the arg-key is probably fine too. If you need to serialize byte streams in the responses to actually get data recorded, some of the functions in the `vcr-clj.clj-http` namespace might help.
